apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
  labels:
    purpose: demonstrate-configmap
spec:
  containers:
  - name: configmap-demo
    image: debian
    command: ["/bin/echo"]
    args: ["Oi $(MESSAGE)"]
    env:
     - name: MESSAGE
       valueFrom:
         configMapKeyRef:
           name: foursys-config
           key: message
  restartPolicy: OnFailure
  